# Header
menu:
  home: /
  #分类: /categories
  #Java: /tags/java
  archives: /archives
  tags: /tags
  # 随笔: /tags/随笔

# SubNav
subnav:
  github: "https://github.com/blademainer"
  #weibo: "#"
  #rss: "#"
  zhihu: "http://www.zhihu.com/people/xiong-ying-qi"
  rss: http://iflowercity.cn/
  #douban: "#"
  #mail: "#"
  #facebook: "#"
  #google: "#"
  #twitter: "#"
  #linkedin: "#"

rss: /atom.xml

# Content
excerpt_link: more
fancybox: true
mathjax: false
tag: true

# 是否开启动画效果
animate: true

# 是否在新窗口打开链接
open_in_new: false

# Miscellaneous
google_analytics: ''
favicon: /favicon.png

#你的头像url
avatar: /images/avatar.jpg
#是否开启分享
share: true
#是否开启多说评论，填写你在多说申请的项目名称 duoshuo: duoshuo-key
#若使用disqus，请在博客config文件中填写disqus_shortname，并关闭多说评论
duoshuo: blademainer
#duoshuo_shortname: blademainer
#是否开启云标签
tagcloud: true
tag: true

#是否开启友情链接
#不开启——
#friends: false
#开启——
friends:
  jia58960: http://jia58960.com/
  password-agent: http://iflowercity.cn/

widgets:
  - category
  - tag
  - tagcloud
  - archives
  - recent_posts

#是否开启“关于我”。
#不开启——
#aboutme: false
#开启——
aboutme: 一杯白开水，虽然无味，但是单纯
